spring.application.name=accessible-care-api

# Actuator
management.endpoints.web.exposure.include=health,info


oci.region=${OCI_REGION:sa-saopaulo-1}
oci.compartment-id=${OCI_COMPARTMENT_ID:}
oci.config.profile=${OCI_CONFIG_PROFILE:DEFAULT}
oci.model-deployment.config-profile=${OCI_MODEL_DEPLOYMENT_CONFIG_PROFILE:DEFAULT}
oci.model-deployment-id=${OCI_MODEL_DEPLOYMENT_ID:}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:mock}
