spring.application.name=accessible-care-api

# Actuator
management.endpoints.web.exposure.include=health,info


model.api.url=${MODEL_API_URL:http://localhost:8000}


oci.region=${OCI_REGION:sa-saopaulo-1}
oci.compartment-id=${OCI_COMPARTMENT_ID:}
oci.config.profile=${OCI_CONFIG_PROFILE:DEFAULT}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:mock}
